"""Изменил модель задач, привязав польователя к создаваемым задачам.

Revision ID: 04de7b03155b
Revises: 703272b78c68
Create Date: 2024-11-27 21:17:47.752145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04de7b03155b"
down_revision: Union[str, None] = "703272b78c68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "user_profile", ["user_id"], ["id"])
    op.drop_column("user_profile", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
