"""add type to category

Revision ID: 271ebffaa2c3
Revises: ebde7791b3f4
Create Date: 2024-11-22 17:05:09.961779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271ebffaa2c3'
down_revision: Union[str, None] = 'ebde7791b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    # ### end Alembic commands ###
