"""Добавил индекс на поле name таблицы tasks

Revision ID: 64b0e874dda8
Revises: 7a2a63f4c9fd
Create Date: 2024-12-09 21:45:08.581945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b0e874dda8'
down_revision: Union[str, None] = '7a2a63f4c9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='tasks')
    op.create_index('name_idx', 'tasks', ['name', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='tasks')
    op.create_index('name_idx', 'tasks', ['name'], unique=True)
    # ### end Alembic commands ###
