"""Добавил индекс на поле name таблицы tasks

Revision ID: 7a2a63f4c9fd
Revises: 04de7b03155b
Create Date: 2024-12-09 21:39:38.729908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2a63f4c9fd'
down_revision: Union[str, None] = '04de7b03155b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_idx', 'tasks', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='tasks')
    # ### end Alembic commands ###
